name: continuous integration of python docker app
on:
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker
        uses: docker/setup-docker-action@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Obtain shortened commit_sha
        shell: bash
        run: |
          echo 'COMMIT_ID=${GITHUB_SHA::6}' >> ${GITHUB_ENV}         

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: aumthakkar/py6app:${{ env.COMMIT_ID }}

    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  cd:
    runs-on: self-hosted
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v6

      - name: Install yq utility 
        run: |
          sudo apt update && apt install python3-pip -y
          pip install yq --break-system-packages
          echo ${{ needs.outputs.ci.commit_id }}
          yq -Yi '.image.tag = "${{ needs.outputs.ci.commit_id }}"' charts/python-app/values.yaml 

      - name: Commit changes to the GitHub repo
        uses: EndBug/add-and-commit@v9
        with:
          message: "pushed the image with tag ${{ needs.outputs.ci.commit_id }}"